.PHONY: setup dev test build up down

setup:
	./scripts/setup.sh

dev:
	docker-compose up

test:
	./scripts/run_tests.sh

build:
	docker-compose build

up:
	docker-compose up -d

down:
	docker-compose down
